name: Build

on:
  push:
  pull_request:
  release:
    types:
      - published

env:
  CIBW_ARCHS_MACOS: x86_64 arm64
  CIBW_SKIP: cp36-* cp37-* pp* *i686

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v2.18.1
      - uses: actions/upload-artifact@v4
        with:
          name: wheelhouse-${{ matrix.os }}
          path: ./wheelhouse/*.whl
  import_library:
    name: Import library on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    needs: [build_wheels]
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - uses: actions/download-artifact@v4
      with:
        name: wheelhouse-${{ matrix.os }}
        path: wheelhouse
    - run: python -m pip install --find-links wheelhouse event_stream
    - run: python -c 'import event_stream'
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*.tar.gz
  upload_pypi:
    name: Upload wheels and sidst to PyPI
    runs-on: ubuntu-latest
    needs: [build_wheels, import_library, build_sdist]
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: wheelhouse
          pattern: wheelhouse-*
          merge-multiple: true
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - run: mv wheelhouse/* dist/
      - uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
